---
title: "Shiny Lissajous Figures with R"
date: "September 12, 2018"
output:  ioslides_presentation
---
## Shiny Lissajous Figures with R
This presentation describes and documents a Shiny app that generates interactive Lissajous
figures.

Lissajous figures are patterns generated by parametric equations
that have the general form:

$x = \sin{At}$

$y = \sin{Bt + C}$

These equations are frequently used to describe complex harmonic motion. The
functions are named after 19th century mathmetician Jules Antoine Lissajous.
For more info, check out Wikipedia:

<a href='https://en.wikipedia.org/wiki/Lissajous_curve'>https://en.wikipedia.org/wiki/Lissajous_curve</a>

## Lissajous Functions in R:
Here's a simple function in R that plots a Lissajous figure:

```{r echo=TRUE}
LisPlot <- function(A, B, C, color){
 
    t <- (0:800)*pi/200   # t ranges from 0 to 4 pi
    x <- sin(A*t)
    y <- sin(B*t + C*pi)
    plot(x,y,type="l",col=color,xlab="x",ylab="y",
         main=paste("A=",i," B=",j),
         xlim=c(-1.1,1.1), ylim=c(-1.1,1.1), asp=1)
}
```

## Sample Lissajous Figures
Here's some sample Lissajous figures with  $C$ set to  $0$:

```{R echo=FALSE}
par(mfrow=c(2,2))
for (i in 2:3)
   for (j in 5:6)
       LisPlot(i,j,0,"blue")
```

## How to Use the App:
- Adjust the sliders to set the values of A, B, and C. 

- The plot will update automatically.

- You can also set the line color using the radio buttons.

Here's a link to the app: 

<a href='https://wkuhlman.shinyapps.io/Lissajous/'>https://wkuhlman.shinyapps.io/Lissajous/</a>

And here's a link to the GitHub repository:

<a href='https://github.com/wkuhlman/lissajous/tree/gh-pages'>
https://github.com/wkuhlman/lissajous/tree/gh-pages</a>
